# Generated by Django 5.1.9 on 2026-06-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_salesorder_guest_email_salesorder_is_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'None'), ('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='NONE', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'পেন্ডিং'), ('CONFIRMED', 'নিশ্চিত'), ('PACKED', 'প্যাক হয়েছে'), ('ASSIGNED', 'ডেলিভারিম্যান নির্ধারিত'), ('ON_THE_WAY', 'পথে আছে'), ('DELIVERED', 'ডেলিভারি হয়েছে'), ('RETURNED', 'ফেরত'), ('CANCELLED', 'বাতিল')], default='PENDING', max_length=20),
        ),
    ]
