# Generated by Django 5.1.9 on 2026-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_shipping_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at']},
        ),
    ]
