# Generated by Django 5.1.9 on 2026-06-05 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_dhaka', models.DecimalField(decimal_places=2, default=60, max_digits=8)),
                ('outside_dhaka', models.DecimalField(decimal_places=2, default=120, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Charge Settings',
            },
        ),
    ]
