# Generated by Django 5.1.9 on 2026-06-09 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_bn', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('equity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_bn'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_bn', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_bn'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'নগদ'), ('CREDIT', 'বাকিতে')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier'),
        ),
    ]
