# Generated by Django 5.1.9 on 2026-06-09 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_partner_supplier_stockmovement_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='PartnerProfitPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_payments', to='api.partner')),
            ],
            options={
                'ordering': ['-year', '-month', 'partner'],
                'unique_together': {('partner', 'year', 'month')},
            },
        ),
    ]
