# Generated by Django 5.1.9 on 2026-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_journalentry_reference_type_supplierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('PURCHASE', 'ক্রয়'), ('SALE', 'বিক্রয়'), ('PAYMENT', 'পেমেন্ট'), ('RETURN', 'ফেরত'), ('ADJUSTMENT', 'সমন্বয়'), ('EXPENSE', 'খরচ'), ('EQUITY', 'ইক্যুইটি'), ('SUPPLIER_PAYMENT', 'সরবরাহকারী পেমেন্ট')], max_length=30),
        ),
    ]
