# Generated by Django 5.1.9 on 2026-06-10 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_journalentry_reference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInvestor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_bn', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Original loan amount', max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate %', max_digits=5)),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-loan_date'],
            },
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('PURCHASE', 'ক্রয়'), ('SALE', 'বিক্রয়'), ('PAYMENT', 'পেমেন্ট'), ('RETURN', 'ফেরত'), ('ADJUSTMENT', 'সমন্বয়'), ('EXPENSE', 'খরচ'), ('EQUITY', 'ইক্যুইটি'), ('SUPPLIER_PAYMENT', 'সরবরাহকারী পেমেন্ট'), ('CAPITAL', 'মূলধন বিনিয়োগ'), ('LOAN_RECEIVED', 'ঋণ গ্রহণ'), ('LOAN_INTEREST', 'সুদ পরিশোধ'), ('LOAN_PRINCIPAL', 'ঋণ পরিশোধ')], max_length=30),
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('INTEREST', 'সুদ পরিশোধ'), ('PRINCIPAL', 'আসল পরিশোধ')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_payments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.loaninvestor')),
            ],
            options={
                'ordering': ['-paid_date'],
            },
        ),
    ]
