# Generated by Django 5.1.9 on 2026-06-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_loaninvestor_alter_journalentry_reference_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('cashback_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='PERCENTAGE', max_length=10)),
                ('cashback_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cashback Settings',
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
