# Generated by Django 5.1.9 on 2026-06-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_cashback_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashback_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=10)),
                ('cashback_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cashback Tier',
                'ordering': ['min_order_amount'],
            },
        ),
        migrations.DeleteModel(
            name='CashbackSetting',
        ),
    ]
