# Generated by Django 5.1.9 on 2026-06-10 05:15

from django.db import migrations, models


def add_cashback_accounts(apps, _schema_editor):
    Account = apps.get_model('api', 'Account')
    Account.objects.get_or_create(
        code='2250',
        defaults={'name_bn': 'ক্যাশব্যাক দেনা', 'name_en': 'Cashback Payable',
                  'account_type': 'LIABILITY', 'is_active': True},
    )
    Account.objects.get_or_create(
        code='6350',
        defaults={'name_bn': 'ক্যাশব্যাক ব্যয়', 'name_en': 'Cashback Expense',
                  'account_type': 'EXPENSE', 'is_active': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cashback_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cashback_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cashback_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.RunPython(add_cashback_accounts, migrations.RunPython.noop),
    ]
