# Generated by Django 5.1.9 on 2026-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_cashback_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
