# Generated by Django 5.1.9 on 2026-06-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_user_phone_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_picture',
            field=models.URLField(blank=True),
        ),
    ]
