# Generated by Django 5.1.9 on 2026-06-14 04:36

from django.db import migrations


def fix_broken_avatars(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    for profile in Profile.objects.exclude(avatar=''):
        name = str(profile.avatar)
        if name.startswith('http://') or name.startswith('https://'):
            profile.google_picture = name
            profile.avatar = ''
            profile.save(update_fields=['avatar', 'google_picture'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_profile_google_picture'),
    ]

    operations = [
        migrations.RunPython(fix_broken_avatars, migrations.RunPython.noop),
    ]
