# Generated by Django 5.1.9 on 2026-06-14 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_fix_broken_google_avatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_picture',
        ),
    ]
