# Generated by Django 5.1.9 on 2026-06-25 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_sitesetting_mail_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_marketing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_package',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PromoEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('NEW_PRODUCT', 'New Product'), ('NEW_PACKAGE', 'New Package'), ('OFFER', 'Offer'), ('GENERAL', 'General')], max_length=20)),
                ('subject_bn', models.CharField(max_length=200)),
                ('subject_en', models.CharField(max_length=200)),
                ('message_bn', models.TextField()),
                ('message_en', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
