# Generated by Django 5.1.9 on 2026-07-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_profile_notify_marketing_profile_notify_new_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'ক্রয়'), ('SALE', 'বিক্রয়'), ('RETURN', 'ফেরত'), ('ADJUSTMENT', 'সমন্বয়'), ('SUPPLIER_RETURN', 'সরবরাহকারীকে ফেরত')], max_length=20),
        ),
    ]
