# Generated by Django 5.1.9 on 2026-07-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=320, null=True, unique=True),
        ),
    ]
