# Generated by Django 5.1.9 on 2026-07-20 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_backfill_product_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('ga4_property_id', models.CharField(blank=True, default='', max_length=64)),
                ('ga4_property_name', models.CharField(blank=True, default='', max_length=255)),
                ('gsc_site_url', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Integration',
            },
        ),
    ]
