# Generated by Django 5.1.9 on 2026-07-28 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_add_courier_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_bn',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_bn',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title_bn',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_bn',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_bn',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_bn', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, null=True, unique=True)),
                ('seo_title_bn', models.CharField(blank=True, default='', max_length=70)),
                ('seo_title_en', models.CharField(blank=True, default='', max_length=70)),
                ('meta_description_bn', models.CharField(blank=True, default='', max_length=170)),
                ('meta_description_en', models.CharField(blank=True, default='', max_length=170)),
                ('focus_keyword', models.CharField(blank=True, default='', max_length=150)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500)),
                ('body_bn', models.TextField(blank=True, default='')),
                ('body_en', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
