# Generated by Django 5.1.9 on 2026-07-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_seo_fields_and_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='faqs',
        ),
    ]
