# Generated by Django 5.1.9 on 2026-07-30 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_roles_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery_person',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__code': 'DELIVERY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
