# Generated by Django 5.1.9 on 2026-07-30 03:58

from uuid import uuid4
from django.db import migrations

# Gaps discovered while retrofitting existing endpoints onto the new
# has_permission(module, action) checks: 'site_settings' had no catalog
# entry at all, and 'cashback' actually has create/delete endpoints that
# the original migration 0049 seed didn't account for.
NEW_PERMISSIONS = [
    ('site_settings', 'view',   'সাইট সেটিংস', 'Site Settings'),
    ('site_settings', 'edit',   'সাইট সেটিংস', 'Site Settings'),
    ('cashback',       'create', 'ক্যাশব্যাক',   'Cashback'),
    ('cashback',       'delete', 'ক্যাশব্যাক',   'Cashback'),
]

ACTION_LABELS = {
    'view':   ('দেখুন', 'View'),
    'create': ('তৈরি করুন', 'Create'),
    'edit':   ('সম্পাদনা', 'Edit'),
    'delete': ('মুছুন', 'Delete'),
}


def add_permissions(apps, schema_editor):
    Permission = apps.get_model('api', 'Permission')
    for module, action, label_bn, label_en in NEW_PERMISSIONS:
        action_bn, action_en = ACTION_LABELS[action]
        Permission.objects.get_or_create(
            module=module, action=action,
            defaults={'id': uuid4(), 'label_bn': f'{label_bn} — {action_bn}', 'label_en': f'{label_en} — {action_en}'},
        )


def remove_permissions(apps, schema_editor):
    Permission = apps.get_model('api', 'Permission')
    for module, action, _, _ in NEW_PERMISSIONS:
        Permission.objects.filter(module=module, action=action).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_deliveryassignment_delivery_person'),
    ]

    operations = [
        migrations.RunPython(add_permissions, remove_permissions),
    ]
