# Generated by Django 5.1.9 on 2026-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_add_accounting_chart_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
