# Generated by Django 5.1.9 on 2026-08-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_add_product_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
