# Generated by Django 5.1.9 on 2026-08-03 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_product_ordering_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaynaBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.CharField(blank=True, default='', max_length=64)),
                ('service_type', models.CharField(choices=[('PUJARI', 'পূজারী'), ('DHAKI', 'ঢাকি'), ('MURTI', 'মূর্তি')], max_length=10)),
                ('event_date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bayna_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
