# Generated by Django 5.1.9 on 2026-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_add_bayna_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baynabooking',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
