# Generated by Django 5.1.9 on 2026-08-07 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_add_bayna_create_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='referral_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=8),
        ),
    ]
