# Generated by Django 5.1.9 on 2026-08-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_add_referral_bonus_amount_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
