# Generated by Django 5.1.9 on 2026-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_add_telegram_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprovider',
            name='access_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courierprovider',
            name='password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courierprovider',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courierprovider',
            name='store_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='courierprovider',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierprovider',
            name='username_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
