# Generated by Django 5.1.9 on 2026-08-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_add_pathao_courier_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierconsignment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
