# Generated by Django 5.1.9 on 2026-08-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_add_courier_consignment_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='extra_charge_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='free_weight_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
