# Generated by Django 5.1.9 on 2026-08-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_add_delivery_weight_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycharge',
            name='extra_charge_per_kg',
        ),
        migrations.RemoveField(
            model_name='deliverycharge',
            name='free_weight_kg',
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='inside_dhaka_weight_tiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='outside_dhaka_weight_tiers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
