# Generated by Django 5.1.9 on 2026-08-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_stock_movement_created_at_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='staff_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
