# Generated by Django 5.1.9 on 2026-08-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'ওয়েবসাইট'), ('AI_CHATBOT', 'ব্রাহ্মণ AI'), ('POS', 'POS')], default='WEBSITE', max_length=20),
        ),
    ]
