# Generated by Django 5.1.9 on 2026-09-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_salesorder_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-created_at'], name='api_salesor_created_e6244a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='api_salesor_status_14b27e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['payment_status'], name='api_salesor_payment_2e2c27_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['shipping_phone'], name='api_salesor_shippin_bd3ba9_idx'),
        ),
    ]
