# Generated by Django 5.1.9 on 2026-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_salesorder_api_salesor_created_e6244a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprovider',
            name='webhook_verification_secret',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
