# Generated by Django 5.1.9 on 2026-09-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'পেন্ডিং'), ('CONFIRMED', 'নিশ্চিত'), ('PACKED', 'প্যাক হয়েছে'), ('ASSIGNED', 'ডেলিভারিম্যান নির্ধারিত'), ('PICKED', 'পিকআপ হয়েছে'), ('ON_THE_WAY', 'পথে আছে'), ('DELIVERED', 'ডেলিভারি হয়েছে'), ('PARTIALLY_DELIVERED', 'আংশিক ডেলিভারি হয়েছে'), ('RETURNED', 'ফেরত'), ('CANCELLED', 'বাতিল')], default='PENDING', max_length=20),
        ),
    ]
