# Generated by Django 5.1.9 on 2026-09-07 11:13

from django.db import migrations, models


def _backfill_segments(apps, schema_editor):
    """Existing rows default to 1 from the AddField above — recompute the
    real value from the stored message text so historical logs show the
    same per-message cost as new ones, instead of silently reading '1'."""
    from api.services.sms_service import sms_segment_count

    SmsLog = apps.get_model('api', 'SmsLog')
    for log in SmsLog.objects.all():
        correct = sms_segment_count(log.message)
        if log.segments != correct:
            log.segments = correct
            log.save(update_fields=['segments'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_whatsappconversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='segments',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(_backfill_segments, migrations.RunPython.noop),
    ]
