# Generated by Django 5.1.9 on 2026-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_product_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='estimated_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
