# Generated by Django 5.1.9 on 2026-09-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_product_and_order_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='inside_dhaka_extra_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='outside_dhaka_extra_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
