# Generated by Django 5.1.9 on 2026-09-08 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_delivery_charge_extra_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='exchanged_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_replacements', to='api.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'পেন্ডিং'), ('CONFIRMED', 'নিশ্চিত'), ('PACKED', 'প্যাক হয়েছে'), ('ASSIGNED', 'ডেলিভারিম্যান নির্ধারিত'), ('PICKED', 'পিকআপ হয়েছে'), ('ON_THE_WAY', 'পথে আছে'), ('DELIVERED', 'ডেলিভারি হয়েছে'), ('PARTIALLY_DELIVERED', 'আংশিক ডেলিভারি হয়েছে'), ('RETURNED', 'ফেরত'), ('EXCHANGED', 'বিনিময় হয়েছে'), ('CANCELLED', 'বাতিল')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_bn', models.TextField(blank=True)),
                ('note_en', models.TextField(blank=True)),
                ('delivery_charge_waived', models.BooleanField(default=False)),
                ('returned_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_created', to=settings.AUTH_USER_MODEL)),
                ('new_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_source', to='api.salesorder')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='api.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.exchange')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_items', to='api.salesorderitem')),
            ],
        ),
    ]
