# Generated by Django 5.1.9 on 2026-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_exchange_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'ওয়েবসাইট'), ('MOBILE_APP', 'মোবাইল অ্যাপ'), ('AI_CHATBOT', 'ব্রাহ্মণ AI'), ('POS', 'POS')], default='WEBSITE', max_length=20),
        ),
    ]
