# Generated by Django 5.1.9 on 2026-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_add_promo_notifications_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='promopush',
            name='delivered_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
