# Generated by Django 5.1.9 on 2026-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_promopush_delivered_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='promopush',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo_pushes/'),
        ),
    ]
