# Generated by Django 5.1.9 on 2026-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_promopush_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_via',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('MOBILE_APP', 'Mobile App')], default='WEBSITE', max_length=10),
        ),
    ]
