# Generated by Django 5.1.9 on 2026-09-22 05:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_user_registered_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_bn', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_integrated', models.BooleanField(default=False)),
                ('charge_type', models.CharField(choices=[('NONE', 'কোনো চার্জ নেই'), ('PERCENT', 'শতাংশ'), ('FLAT', 'নির্দিষ্ট পরিমাণ')], default='NONE', max_length=10)),
                ('charge_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='gateway_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
