# Generated by Django 5.1.9 on 2026-09-22 05:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_add_payment_methods_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='mobile_app_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_app_order_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'ক্যাশ অন ডেলিভারি'), ('SSLCOMMERZ', 'অনলাইন পেমেন্ট (SSLCommerz)'), ('BKASH', 'বিকাশ'), ('NAGAD', 'নগদ'), ('STRIPE', 'স্ট্রাইপ (কার্ড)'), ('ONLINE', 'অনলাইন পেমেন্ট')], default='COD', max_length=10),
        ),
    ]
