# Generated by Django 5.1.9 on 2026-09-22 05:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_salesorder_mobile_app_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='free_delivery_min_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
