# Generated by Django 5.1.9 on 2026-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_sitesetting_free_delivery_min_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='payment_methods/'),
        ),
    ]
