# Generated by Django 5.1.9 on 2026-09-23 05:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_paymentmethod_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tran_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'অপেক্ষমান'), ('CONFIRMED', 'নিশ্চিত'), ('FAILED', 'ব্যর্থ'), ('CANCELLED', 'বাতিল')], default='PENDING', max_length=20)),
                ('is_guest', models.BooleanField(default=False)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_name_bn', models.CharField(max_length=200)),
                ('shipping_name_en', models.CharField(blank=True, max_length=200)),
                ('shipping_phone', models.CharField(max_length=15)),
                ('shipping_address_bn', models.TextField()),
                ('shipping_address_en', models.TextField(blank=True)),
                ('shipping_district', models.CharField(max_length=100)),
                ('shipping_thana', models.CharField(max_length=100)),
                ('shipping_post_code', models.CharField(max_length=10)),
                ('notes_bn', models.TextField(blank=True)),
                ('items_snapshot', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_order_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_app_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('gateway_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cashback_used_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_method', models.CharField(max_length=20)),
                ('source', models.CharField(default='WEBSITE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_checkout', to='api.salesorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
