# Generated by Django 5.1.9 on 2026-09-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_promocode_pendingcheckout_promo_code_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='mobile_app_order_discount_percent',
        ),
    ]
