# Generated by Django 5.1.9 on 2026-09-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_remove_sitesetting_mobile_app_order_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='scope',
            field=models.CharField(choices=[('MOBILE_APP', 'শুধু অ্যাপ'), ('WEBSITE', 'শুধু ওয়েবসাইট')], default='MOBILE_APP', max_length=20),
        ),
    ]
