# Generated by Django 5.1.9 on 2026-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_add_promo_codes_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='scope',
            field=models.CharField(choices=[('MOBILE_APP', 'শুধু অ্যাপ'), ('WEBSITE', 'শুধু ওয়েবসাইট'), ('BOTH', 'অ্যাপ ও ওয়েবসাইট উভয়ই')], default='MOBILE_APP', max_length=20),
        ),
    ]
