# Generated by Django 5.1.9 on 2026-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_alter_promocode_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_badge_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_badge_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trendy_badge_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
