# Generated by Django 5.1.9 on 2026-10-02 18:32

from django.db import migrations, models


def backfill_new_badge_set_at(apps, schema_editor):
    # Existing products tagged 'new' before this field existed have no
    # recorded "when was it set" — best approximation is their creation
    # date, since that's when a product is normally first tagged 'new'.
    Product = apps.get_model('api', 'Product')
    Product.objects.filter(badges__contains=['new'], new_badge_set_at__isnull=True).update(
        new_badge_set_at=models.F('created_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_alter_promocode_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_badge_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_new_badge_set_at, migrations.RunPython.noop),
    ]
