# Generated by Django 5.1.9 on 2026-10-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_clear_time_boxed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
