# Generated by Django 5.1.9 on 2026-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_user_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_login_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
