# Generated by Django 5.1.9 on 2026-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_site_setting_login_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_provider',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook')], default='MANUAL', max_length=10),
        ),
    ]
