# Generated by Django 5.1.9 on 2026-10-06 14:49, hand-edited to interleave
# a data migration BEFORE the old color_bn/color_en columns are dropped —
# see the big docstring on `_convert_existing_colors` below for why.

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _convert_existing_colors(apps, schema_editor):
    """Seeds the Color/Size attribute-type library and converts every
    product's existing (free-text, display-only) ProductImage.color_bn/
    color_en tags into real VariantAttributeValue + ProductVariant rows —
    stock starts at 0 (no historical per-color split exists to recover;
    see this migration's follow-up note). Must run BEFORE the RemoveField
    operations below drop color_bn/color_en, so it's placed mid-migration
    rather than as its own later migration — within one migration file,
    apps.get_model() returns the historical model state as of that exact
    point in the operations list, and the old columns are still there
    until the RemoveField ops that follow this one.

    CartItem/SalesOrderItem's old color_bn/color_en are copied straight
    into variant_label_bn/en (no FK resolution attempted) — live carts are
    transient and historical order items must never change their display
    under a later edit to variants/values, so a plain text copy is the
    correct, final snapshot for both, not a placeholder.
    """
    Product               = apps.get_model('api', 'Product')
    ProductImage          = apps.get_model('api', 'ProductImage')
    CartItem              = apps.get_model('api', 'CartItem')
    SalesOrderItem        = apps.get_model('api', 'SalesOrderItem')
    VariantAttributeType  = apps.get_model('api', 'VariantAttributeType')
    VariantAttributeValue = apps.get_model('api', 'VariantAttributeValue')
    ProductVariant        = apps.get_model('api', 'ProductVariant')
    ProductVariantValue   = apps.get_model('api', 'ProductVariantValue')

    color_type, _ = VariantAttributeType.objects.get_or_create(
        code='color',
        defaults={'name_bn': 'রং', 'name_en': 'Color', 'has_bilingual_values': True, 'is_active': True},
    )
    VariantAttributeType.objects.get_or_create(
        code='size',
        defaults={'name_bn': 'সাইজ', 'name_en': 'Size', 'has_bilingual_values': False, 'is_active': True},
    )

    tagged_product_ids = (
        ProductImage.objects.exclude(color_bn='', color_en='').values_list('product_id', flat=True).distinct()
    )
    for product in Product.objects.filter(id__in=list(tagged_product_ids)):
        images = list(product.images.exclude(color_bn='', color_en=''))
        pairs = {}
        for img in images:
            key = (img.color_bn, img.color_en)
            pairs.setdefault(key, []).append(img)

        for (color_bn, color_en), imgs in pairs.items():
            value_en = color_en or color_bn
            value, _ = VariantAttributeValue.objects.get_or_create(
                attribute_type=color_type, value_en=value_en,
                defaults={'value_bn': color_bn, 'is_active': True},
            )
            variant = ProductVariant.objects.create(product=product, is_active=True)
            ProductVariantValue.objects.create(variant=variant, attribute_value=value)
            for img in imgs:
                img.visual_value_id = value.id
                img.save(update_fields=['visual_value_id'])

        product.visual_attribute_type_id = color_type.id
        product.save(update_fields=['visual_attribute_type_id'])

    for item in CartItem.objects.exclude(color_bn='', color_en=''):
        item.variant_label_bn = item.color_bn
        item.variant_label_en = item.color_en
        item.save(update_fields=['variant_label_bn', 'variant_label_en'])

    for item in SalesOrderItem.objects.exclude(color_bn='', color_en=''):
        item.variant_label_bn = item.color_bn
        item.variant_label_en = item.color_en
        item.save(update_fields=['variant_label_bn', 'variant_label_en'])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_fix_color_bilingual_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAttributeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_bn', models.CharField(max_length=40)),
                ('name_en', models.CharField(max_length=40)),
                ('code', models.SlugField(unique=True)),
                ('has_bilingual_values', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_label_bn',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_label_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='variant_label_bn',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='variant_label_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_suffix', models.CharField(blank=True, default='', max_length=20)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.productvariant'),
        ),
        migrations.AddField(
            model_name='productpackageitem',
            name='component_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.productvariant'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.productvariant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='api.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productpackageitem',
            unique_together={('package', 'component', 'component_variant')},
        ),
        migrations.AddField(
            model_name='product',
            name='visual_attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.variantattributetype'),
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_bn', models.CharField(blank=True, default='', max_length=40)),
                ('value_en', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='api.variantattributetype')),
            ],
            options={
                'ordering': ['value_en'],
                'unique_together': {('attribute_type', 'value_en')},
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='visual_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.variantattributevalue'),
        ),
        migrations.CreateModel(
            name='ProductVariantValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='api.productvariant')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.variantattributevalue')),
            ],
            options={
                'unique_together': {('variant', 'attribute_value')},
            },
        ),

        # ── Data migration: must run while color_bn/color_en still exist ──
        migrations.RunPython(_convert_existing_colors, _noop_reverse),

        # ── Now safe to drop the old free-text columns ──
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color_bn',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='color_bn',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='color_bn',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='color_en',
        ),
    ]
