# Generated by Django 5.1.9 on 2026-10-07 08:40

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_variantattributetype_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        # Required before any GinIndex(..., opclasses=['gin_trgm_ops']) below
        # — lets Postgres accelerate icontains/substring search with a GIN
        # index instead of a sequential scan.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['new_badge_set_at'], name='api_product_new_bad_b194ce_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['trendy_badge_set_at'], name='api_product_trendy__d95c64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['flash_sale_badge_set_at'], name='api_product_flash_s_77c330_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['badges'], name='api_product_badges_275157_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_bn'], name='product_name_bn_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='product_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sku'], name='product_sku_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved'], name='api_review_product_8eedd2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['source'], name='api_salesor_source_51b723_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['order_number'], name='order_number_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['shipping_phone'], name='shipping_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['shipping_name_bn'], name='shipping_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'movement_type', '-created_at'], name='api_stockmo_product_ad3226_idx'),
        ),
    ]
