# Generated by Django 5.1.9 on 2026-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_product_api_product_new_bad_b194ce_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_courier_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
