# Generated by Django 5.1.9 on 2026-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_sitesetting_telegram_courier_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_charge_waived',
            field=models.BooleanField(default=False),
        ),
    ]
