# Generated by Django 5.1.9 on 2026-10-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_salesorder_delivery_charge_waived'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprovider',
            name='cod_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
