"""
Management command: fix_order_journals

Deletes all existing PAYMENT and RETURN journal entries generated by the order
service and re-creates them using the corrected logic:
  - Delivery charge is excluded (it goes to the delivery person, not platform).
  - Cash / Sales Revenue = subtotal - discount_amount (net product revenue only).
  - Each entry is perfectly balanced: Dr Cash = Cr Revenue, Dr COGS = Cr Inventory.

Usage:
    python manage.py fix_order_journals
    python manage.py fix_order_journals --dry-run   # preview only, no changes
"""

from decimal import Decimal
from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils import timezone
from api.models import Account, JournalEntry, JournalLine, SalesOrder, User


def _acct(code):
    try:
        return Account.objects.get(code=code)
    except Account.DoesNotExist:
        return None


def _next_entry_number(today):
    prefix = f'JE-{today:%Y%m%d}-'
    last   = JournalEntry.objects.filter(entry_number__startswith=prefix).count()
    return f'{prefix}{last + 1:04d}'


def _make_payment_lines(order):
    """Returns list of (code, debit, credit) for a sale journal."""
    cogs    = sum(
        item.product.cost_price * item.quantity
        for item in order.items.select_related('product')
    )
    revenue = order.subtotal - (order.discount_amount or Decimal('0'))
    return [
        ('1000', revenue, Decimal('0')),   # Dr Cash
        ('5000', cogs,    Decimal('0')),   # Dr COGS
        ('4000', Decimal('0'), revenue),   # Cr Sales Revenue
        ('1300', Decimal('0'), cogs),      # Cr Inventory
    ]


def _make_return_lines(order):
    """Returns list of (code, debit, credit) for a return journal."""
    cogs    = sum(
        item.product.cost_price * item.quantity
        for item in order.items.select_related('product')
    )
    revenue = order.subtotal - (order.discount_amount or Decimal('0'))
    return [
        ('4000', revenue,      Decimal('0')),  # Dr Sales Revenue
        ('1300', cogs,         Decimal('0')),  # Dr Inventory
        ('1000', Decimal('0'), revenue),       # Cr Cash
        ('5000', Decimal('0'), cogs),          # Cr COGS
    ]


class Command(BaseCommand):
    help = 'Re-creates PAYMENT and RETURN journals without delivery charge'

    def add_arguments(self, parser):
        parser.add_argument('--dry-run', action='store_true', help='Preview without writing')

    @transaction.atomic
    def handle(self, *args, **options):
        dry = options['dry_run']
        today = timezone.now().date()

        admin = User.objects.filter(role='ADMIN', is_active=True).first()
        if not admin:
            self.stderr.write('No active admin user found. Aborting.')
            return

        # ── 1. Delete all existing PAYMENT / RETURN order journals ────────────
        bad = JournalEntry.objects.filter(reference_type__in=['PAYMENT', 'RETURN'])
        count_deleted = bad.count()
        self.stdout.write(f'Found {count_deleted} PAYMENT/RETURN journal entries to delete.')
        if not dry:
            bad.delete()

        # ── 2. Re-create PAYMENT journals for all DELIVERED orders ────────────
        delivered = SalesOrder.objects.filter(status='DELIVERED').prefetch_related('items__product')
        payment_count = 0
        for order in delivered:
            if dry:
                self.stdout.write(f'  [DRY] Would create PAYMENT journal for {order.order_number}')
                continue
            entry = JournalEntry.objects.create(
                entry_number=_next_entry_number(today),
                reference_type='PAYMENT',
                reference_id=order.id,
                description_bn=f'বিক্রয় ও পেমেন্ট — {order.order_number}',
                description_en=f'Sale & Payment — {order.order_number}',
                created_by=admin,
                is_posted=True,
            )
            for code, debit, credit in _make_payment_lines(order):
                acct = _acct(code)
                if acct and (debit or credit):
                    JournalLine.objects.create(
                        journal_entry=entry, account=acct, debit=debit, credit=credit,
                    )
            payment_count += 1

        # ── 3. Re-create RETURN journals for all RETURNED orders ──────────────
        returned = SalesOrder.objects.filter(status='RETURNED').prefetch_related('items__product')
        return_count = 0
        for order in returned:
            if dry:
                self.stdout.write(f'  [DRY] Would create PAYMENT + RETURN journals for {order.order_number}')
                continue
            # A returned order first had a payment journal (sale happened), then a return
            pay_entry = JournalEntry.objects.create(
                entry_number=_next_entry_number(today),
                reference_type='PAYMENT',
                reference_id=order.id,
                description_bn=f'বিক্রয় ও পেমেন্ট — {order.order_number}',
                description_en=f'Sale & Payment — {order.order_number}',
                created_by=admin,
                is_posted=True,
            )
            for code, debit, credit in _make_payment_lines(order):
                acct = _acct(code)
                if acct and (debit or credit):
                    JournalLine.objects.create(
                        journal_entry=pay_entry, account=acct, debit=debit, credit=credit,
                    )
            ret_entry = JournalEntry.objects.create(
                entry_number=_next_entry_number(today),
                reference_type='RETURN',
                reference_id=order.id,
                description_bn=f'পণ্য ফেরত — {order.order_number}',
                description_en=f'Goods Return — {order.order_number}',
                created_by=admin,
                is_posted=True,
            )
            for code, debit, credit in _make_return_lines(order):
                acct = _acct(code)
                if acct and (debit or credit):
                    JournalLine.objects.create(
                        journal_entry=ret_entry, account=acct, debit=debit, credit=credit,
                    )
            return_count += 1

        if dry:
            self.stdout.write(self.style.WARNING('DRY RUN — no changes written.'))
        else:
            self.stdout.write(self.style.SUCCESS(
                f'Done. Deleted {count_deleted} old entries. '
                f'Re-created {payment_count} PAYMENT + {return_count} RETURNED order journal pairs.'
            ))
